build errors
```
npm run build

> fff@251.29.2 build
> next build

  ▲ Next.js 14.2.23
  - Environments: .env.local

   Creating an optimized production build ...
 ✓ Compiled successfully

./app/ui/detail/morpheme-section.tsx
46:8  Warning: React Hook useEffect has a missing dependency: 'parentId'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
   Linting and checking validity of types  ..Failed to compile.

./app/lib/factory/data/db-client-factory.ts:1:35
Type error: Cannot find module './db-clinet-interface' or its corresponding type declarations.

> 1 | import { DbClientInterface } from "./db-clinet-interface";
    |                                   ^
  2 | import { DbClientPostgresImpl } from "./db-client-postgres-impl";
  3 | import { Primitive, SqlInterface } from "@/app/lib/factory/data/sql-interface";
  4 | import { FieldDef, sql as vercelSql } from "@vercel/postgres";
Static worker exited with code: 1 and signal: null
```